apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: web
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "1"
      limits:
        memory: "128Mi"
        cpu: "2"
    ports:
      - containerPort: 80
    command: ["nginx"]
    args: ["-g daemonoff;" , "-q"]